# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'Goodz' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Goodz
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftLint'
  pod 'FSCalendar'
  pod 'Charts'
  pod 'Alamofire'
  pod 'DZNEmptyDataSet'
  pod 'GoogleSignIn'
  pod 'GoogleAnalytics'
  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/DynamicLinks'
  pod 'SDWebImage'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Performance'
  pod 'Firebase/Messaging'
  pod 'FirebaseAnalytics'
  pod 'SDWebImage'
  pod 'Cosmos'
  pod 'ReachabilitySwift'
  pod 'AWSS3'
  pod 'SwiftGifOrigin'
  pod "BSImagePicker"
  
  target 'GoodzTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'GoodzUITests' do
    # Pods for testing
  end

end



post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end
end
