//
//  Labels.swift
//  Goodz
//
//  Created by Akruti on 02/01/24.
//

import Foundation
struct Labels {
    static let emailNotExistInYourAccount = appLANG.retrive(label: "email_not_exist_in_your_account")
    static let invalidEmailOrPassword = appLANG.retrive(label: "invalid_email_or_password")
    static let emailAlreadyExistInSystem = appLANG.retrive(label: "email_already_exist_in_system")
    static let emailAlreadyExistInSystemWithOtherSigninMethods = appLANG.retrive(label: "email_already_exist_in_system_with_other_Signin_methods")
    static let male = appLANG.retrive(label: "male")
    static let security = appLANG.retrive(label: "security")
    static let viewMore = appLANG.retrive(label: "view_more")
    static let privacyPolicy : String = appLANG.retrive(label:"privacy_Policy")
    static let commitmentContentOne : String = appLANG.retrive(label: "Goodz lets you pick your favorite brands and products to tailor your news feed content and match your preferences with the right products.")
    static let appname: String = appLANG.retrive(label: "Goodz")
    static let goodzDeals = appLANG.retrive(label:"goodz_Deals")
    static let store : String = appLANG.retrive(label: "store")
    static let gOODZPRO : String = appLANG.retrive(label: "gOODZ_PRO")
    static let goodzLetsYouPickYourFavoriteBrandsAndProductstoTailorYourNewsFeedContentAndMatchYourPreferencesWithTheRightProducts : String = appLANG.retrive(label: "Goodz lets you pick your favorite brands and products to tailor your news feed content and match your preferences with the right products.")
    static let contactUs : String = appLANG.retrive(label: "contact_Us")
    static let sellingOnGoodz : String = appLANG.retrive(label: "selling_on_goodz")
    static let buyingOnGoodz : String = appLANG.retrive(label: "buying_on_goodz")
    static let aboutUs : String = appLANG.retrive(label: "about_Us")
    static let committedToASustainable : String =  appLANG.retrive(label:"commitment_head_one") ///Admin
    static let aMessageFromGoodz : String = appLANG.retrive(label:"commitment_head_two") ///Admin
    static let thatsWhyWeHaveTaken : String = appLANG.retrive(label:"commitment_content_two") ///Admin
    static let goodz : String = appLANG.retrive(label:"gOODZ")
    static let haveSendAnewOffer : String = appLANG.retrive(label: "have send a new offer")
    static let minimumProductsRequiredBoostStoreAlert : String = appLANG.retrive(label: "minimum_products_required_boost_store_alert")
    static let buy = appLANG.retrive(label: "buy") ///Admin
    static let sell = appLANG.retrive(label: "sell") ///Admin
}

extension Labels {
    static let getUpToOff : String = appLANG.retrive(label: "get_up_to_50_off")
    static let hidden : String = appLANG.retrive(label: "hidden")
    static let pleaseAddPhotoOrVideoOfYourItem : String = appLANG.retrive(label: "please_add_photo_or_video_of_your_item")
    static let yourProfileUpdatedSuccessfully : String = appLANG.retrive(label: "your_profile_updated_successfully")
    static let toUseAdsFeatureYouShouldHaveAtLeastOneProductUploadedInYourStore : String = appLANG.retrive(label: "to_use_ads_feature_you_should_have_at_least_one_product_uploaded_in_your_store")
    static let weRequireYourEmiratesIdForAccountVerificationBecauseItIsRequiredByOurPaymentProvider : String = appLANG.retrive(label: "we_require_your_emirates_id_for_account_verification,_because_it_is_required_by_our_payment_provider…")
        static let yourSecurityPriorityValue : String = appLANG.retrive(label: "your_security_priority_value")
        static let pleaseSelectFrontDocument : String = appLANG.retrive(label: "please_select_front_document")
        static let pleaseSelectCompanyLetterHead : String = appLANG.retrive(label: "please_select_company_letter_head")
        static let pleaseSelectBackDocument : String = appLANG.retrive(label: "please_select_back_document")
        static let pleaseSelectTradeLicense : String = appLANG.retrive(label: "please_select_trade_license")
        static let pleaseAcceptPrivacyPolicy : String = appLANG.retrive(label: "please_accept_privacy_policy")
        static let aSecondLifeToThisItemsContributesToSave : String = appLANG.retrive(label: "a_second_life_to_this_items_contributes_to_save")
    //    static let hidden : String = appLANG.retrive(label: "hidden")
}

extension Labels {
    // api message
        static let otpExpired : String = appLANG.retrive(label: "otp_expired")
        static let emailAlreadyExists : String = appLANG.retrive(label: "email_already_exists")
        static let passwordNotMatch : String = appLANG.retrive(label: "password_not_match")
        static let deletedAcount : String = appLANG.retrive(label: "deleted_acount")
        static let inactiveAccount : String = appLANG.retrive(label: "inactive_account")
    //    static let hidden : String = appLANG.retrive(label: "hidden")
    
}
extension Labels {
    /// Admin panel labels
    static let howItworks : String = appLANG.retrive(label: "how_it_works")
    static let fAQ : String = appLANG.retrive(label: "faq")
    static let areYouSureYouWantToLogout = appLANG.retrive(label: "are_you_sure_you_want_to_logout")
    static let telr = appLANG.retrive(label:"payment_gateway_name")
    static let areYouSureYouWantToDeleteYourAccount = appLANG.retrive(label: "are_you_sure_you_want_to_delete_account")
    static let areYouSureYouWantToDeleteAddress = appLANG.retrive(label: "are_you_sure_you_want_to_delete_address")
    static let noDataFound : String = appLANG.retrive(label: "no_data_found")
    static let following = appLANG.retrive(label: "following")
    static let follow = appLANG.retrive(label: "follow")
    static let noReviewsYet : String = appLANG.retrive(label: "no_reviews_yet")
    static let noFollowers  : String = appLANG.retrive(label: "no_followers")
    static let reviews : String = appLANG.retrive(label: "reviews")
    static let productDescription = appLANG.retrive(label: "product_description")
    static let boost : String = appLANG.retrive(label: "boost")
    static let boosted : String = appLANG.retrive(label: "boosted")
    static let uRL360Degree : String = appLANG.retrive(label: "equirectangular_url")
    static let cm = appLANG.retrive(label: "cm")
    static let kg = appLANG.retrive(label: "kg")
    // sell item
    static let addPhotosAndVideosOfYourItem = appLANG.retrive(label: "add_photos_and_videos_of_your_item")
    static let brandStar : String = appLANG.retrive(label: "brand_star")
    static let categoryStar : String = appLANG.retrive(label: "category_star")
    static let conditionStar : String = appLANG.retrive(label: "condition_star")
    static let pleaseEnterSellingPrice  = appLANG.retrive(label: "please_enter_selling_price")
    static let uploadUpToPicturesAndVideos = appLANG.retrive(label: "upload_up_to_pictures_and_videos")
    static let addPhotoAndVideoDesc1 = appLANG.retrive(label: "add_photo_and_video_desc_1")
    static let addPhotoAndVideoDesc2 = appLANG.retrive(label: "add_photo_and_video_desc_2")
    static let addPhotoAndVideoDesc3 = appLANG.retrive(label: "image_size_recommended")
    static let the_latest_arrivals = appLANG.retrive(label: "the_latest_arrivals")
    static let pleaseEnterProductTitle  = appLANG.retrive(label: "please_enter_product_title")
    static let sellFasterByFillingInTheDimensions = appLANG.retrive(label: "sell_faster_by_filling_in_the_dimensions")
    static let widthCm = appLANG.retrive(label: "width_cm")
    static let heightCm = appLANG.retrive(label: "height_cm")
    static let lengthCm = appLANG.retrive(label: "length_cm")
    static let weightKg = appLANG.retrive(label: "weight_kg")
    static let width = appLANG.retrive(label: "width")
    static let height = appLANG.retrive(label: "height")
    static let length = appLANG.retrive(label: "length")
    static let weight = appLANG.retrive(label: "weight")
    static let uploadYourOriginalInvoice = appLANG.retrive(label: "upload_your_original_invoice")
    static let fillAllTheDimensions = appLANG.retrive(label: "fill_all_the_dimensions")
    static let yourPickUpAddress = appLANG.retrive(label: "your_pick_up_address")
    static let yourDeliveryAddress = appLANG.retrive(label: "your_delivery_address")
    static let enterPrice = appLANG.retrive(label: "enter_price")
    static let forYou = appLANG.retrive(label: "for_you")
    static let sellYourItem = appLANG.retrive(label: "sell_your_item")
    static let titleStar = appLANG.retrive(label: "title_star")
    static let descriptionStar = appLANG.retrive(label: "description_star")
    static let dimensionsStar = appLANG.retrive(label: "dimensions_star")
    static let dimension = appLANG.retrive(label: "dimension")
    static let color = appLANG.retrive(label: "color")
    static let material = appLANG.retrive(label: "material")
    static let invoice = appLANG.retrive(label: "invoice")
    static let warranty = appLANG.retrive(label: "warranty")
    static let optional = appLANG.retrive(label: "optional")
    static let upload = appLANG.retrive(label: "upload")
    static let address = appLANG.retrive(label: "address")
    static let change = appLANG.retrive(label: "change")
    static let deliveryMethodTitle = appLANG.retrive(label: "delivery_method_title")
    static let youCanChoseSeveralOptionsMsg = appLANG.retrive(label: "you_can_chose_several_options_msg")
    static let addThePrice = appLANG.retrive(label: "add_the_price")
    static let brandNewPrice = appLANG.retrive(label: "brand_new_price")
    static let sellingPriceStar = appLANG.retrive(label: "selling_price_star")
    static let enterSellingPrice = appLANG.retrive(label: "enter_selling_price")
    static let priceYouWillEarn = appLANG.retrive(label: "price_you_will_earn")
    static let pricingSuggestion = appLANG.retrive(label: "pricing_suggestion")
    static let sellFaster = appLANG.retrive(label: "sell_faster")
    static let sellSlower = appLANG.retrive(label: "sell_slower")
    static let toIntegrateGoodzDealShould = appLANG.retrive(label: "to_integrate_goodz_deal_should")
    static let validateModifications = appLANG.retrive(label: "validate_modifications")
    static let originalBrandNewPriceOfYourItem = appLANG.retrive(label: "original_brand_new_price_of_your_item")
    static let editSellItem : String = appLANG.retrive(label:"edit_sell_item")
    static let publicPriceOnGoodz = appLANG.retrive(label: "public_price_on_goodz")
    static let sellItemAcceptedTermsAndCondition = appLANG.retrive(label: "sell_item_accepted_terms_and_condition")
    static let t_and_c = appLANG.retrive(label: "t_and_c")
    static let sellingPriceIsDiscountFromTheBrandNewPrice = appLANG.retrive(label: "selling_price_is_discount_from_the_brand_new_price")
    static let customization = appLANG.retrive(label: "customization")
    static let brands = appLANG.retrive(label: "brands")
    static let reset : String = appLANG.retrive(label: "reset")
    static let save : String = appLANG.retrive(label: "save")
    static let searchBrand : String = appLANG.retrive(label: "search_brand")
    static let saveCustomizationSuccessfully : String = appLANG.retrive(label: "save_customization_successfully")
    static let resetCustomizationSuccessfully : String = appLANG.retrive(label: "reset_customization_successfully")
    static let categories : String = appLANG.retrive(label: "categories")
    static let nothingHere : String = appLANG.retrive(label: "nothing_here")
    
    static let search : String = appLANG.retrive(label: "search")
    static let searchWithUsername : String = appLANG.retrive(label: "search_with_username")
    // Priority contact Details
    static let attachFile : String = appLANG.retrive(label: "attach_file")
    static let pleaseEnterName : String = appLANG.retrive(label: "please_enter_name")
    static let pleaseEnterSubject : String = appLANG.retrive(label: "please_enter_subject")
    static let pleaseEnterMessage : String = appLANG.retrive(label: "please_enter_message")
    static let name : String = appLANG.retrive(label: "name")
    static let message : String = appLANG.retrive(label: "message")
    static let subject : String = appLANG.retrive(label: "subject")
    static let enterName : String = appLANG.retrive(label: "enter_name")
    static let enterEmail : String = appLANG.retrive(label: "enter_email")
    static let enterSubject : String = appLANG.retrive(label: "enter_subject")
    static let priorityContact : String = appLANG.retrive(label: "priority_contact")
    static let enterMessageHere : String = appLANG.retrive(label: "enter_message_here")
    static let priorityContactAddedSuccessfully : String = appLANG.retrive(label: "priority_contact_added_successfully")
    static let pleaseUploadMedia : String = appLANG.retrive(label: "please_upload_media")
   // upload docmument
    static let iHerebyCertifiedThatAll : String = appLANG.retrive(label:"i_hereby_certified_that_all_the_information_transmitted_are_accurate_and_accept_goodz_general_t_c")
    /// Search
    static let searchProduct = appLANG.retrive(label:"search_products")
    static let searchStores = appLANG.retrive(label:"search_stores")
    /// my account
    static let appVersion : String = appLANG.retrive(label: "app_version")
    /// order
    static let byRegisteringIConfirmThatIAcceptGoodzs : String = appLANG.retrive(label: "by_registering_I_confirm_that_I_accept_Goodzs_Terms_and_Conditions_have_read_the_Privacy_Policy_and_I_am_at_least_18_years_old")
    static let haveReadThePrivacyPolicyAndIAmAtLeast18YearsOld : String = appLANG.retrive(label: "have_read_the_privacy_policy_and_i_am_at_least_18_years_old")
    static let termsCondition  : String = appLANG.retrive(label: "terms_conditions")
    /// Auth
    static let pleaseCreateYourAccount = appLANG.retrive(label: "please_create_your_account")
    static let alreadyUser = appLANG.retrive(label: "already_user")
    static let pleaseEnterUsername = appLANG.retrive(label: "please_enter_username")
    static let pleaseSelectCountryCode = appLANG.retrive(label: "please_select_country_code")
    static let enterYourEmail = appLANG.retrive(label: "enter_your_email")
    static let backToLogin = appLANG.retrive(label: "back_to_login")
    static let verificationCode = appLANG.retrive(label: "verification_code")
    static let enterVerificationCodeWeJustSentViaEmail : String = appLANG.retrive(label: "enter_verification_code_we_just_sent_via_email")
    static let expiringIn = appLANG.retrive(label: "expiring_in")
    static let username : String = appLANG.retrive(label: "username")
    static let verify = appLANG.retrive(label: "verify")
    static let resend = appLANG.retrive(label: "resend")
    static let pleaseEnterOtp = appLANG.retrive(label: "please_enter_otp")
    static let skip = appLANG.retrive(label: "skip")
    static let pleaseLoginToYourAccount = appLANG.retrive(label: "please_login_to_your_account")
    static let selectAnAccountToSigninWith = appLANG.retrive(label: "select_an_account_to_sign_in_with")
    static let email = appLANG.retrive(label: "email")
    static let password = appLANG.retrive(label: "password")
    static let login = appLANG.retrive(label: "login")
    static let loginWithAnotherAcc = appLANG.retrive(label: "login_with_another_account")
    static let continueWith = appLANG.retrive(label: "continue_with")
    static let signUp = appLANG.retrive(label: "sign_up")
    static let pleaseEnterValidEmail = appLANG.retrive(label: "please_enter_valid_email")
    static let pleaseEnterEmail = appLANG.retrive(label: "please_enter_email")
    static let pleaseEnterPassword = appLANG.retrive(label: "please_enter_password")
    static let google : String = appLANG.retrive(label: "google")
    static let facebook : String = appLANG.retrive(label: "facebook")
    static let apple : String = appLANG.retrive(label: "apple")
    static let forgotPasswordQue : String = appLANG.retrive(label: "forgot_password_que")
    static let oR : String = appLANG.retrive(label: "or")
    static let send = appLANG.retrive(label: "send")
    static let sendYourMessage = appLANG.retrive(label: "send_your_message")
    static let somethingWentWrong = appLANG.retrive(label: "something_went_wrong")
    static let appName = appLANG.retrive(label: "app_name")
    static let enterEmailId = appLANG.retrive(label: "enter_email_id")
    static let submit = appLANG.retrive(label: "submit")
    static let cancel = appLANG.retrive(label: "cancel")
    static let somethingWentWrongPleaseLoginAgain = appLANG.retrive(label: "your_account_has_been_logged_in_on_another_device_message_should_be_shown")
    static let pleaseUploadProductMedia  = appLANG.retrive(label: "please_upload_product_media")
    static let pleaseEnterProductDescription  = appLANG.retrive(label: "please_enter_product_description")
    static let pleaseSelectBrand  = appLANG.retrive(label: "please_select_brand")
    static let pleaseSelectCondition  = appLANG.retrive(label: "please_select_condition")
    static let pleaseSelectCategory  = appLANG.retrive(label: "please_select_category")
    static let pleaseEnterHeight  = appLANG.retrive(label: "please_enter_product's_height")
    static let pleaseEnterDepth = appLANG.retrive(label: "please_enter_product's_depth")
    static let pleaseEnterWidth  = appLANG.retrive(label: "please_enter_product's_width")
    static let pleaseEnterWeight  = appLANG.retrive(label: "please_enter_product's_weight")
    
    static let pleaseAgreeWithTermsAndCondition  = appLANG.retrive(label: "please_agree_with_terms_and_condition")
    static let pleaseSelectPickupAddress  = appLANG.retrive(label: "please_select_pickup_address")
    static let pleaseSelectDeliveryMethod  = appLANG.retrive(label: "please_select_delivery_method")
    static let pleaseEnterSellingPriceForYou  = appLANG.retrive(label: "please_enter_selling_price_for_you")
    static let pleaseEnterFullName = appLANG.retrive(label: "please_enter_full_name")
    static let pleaseEnterPhoneNumber = appLANG.retrive(label: "please_enter_phone_number")
    static let pleaseEnterStreetAddress = appLANG.retrive(label: "please_enter_street_address")
    static let please_enter_comapny_name = appLANG.retrive(label: "please_enter_comapny_name")
    static let pleaseEnterFloor = appLANG.retrive(label: "please_enter_floor")
    static let selectCity = appLANG.retrive(label: "select_city")
    static let selectArea = appLANG.retrive(label: "select_area")
    static let addNew = appLANG.retrive(label: "add_new")
    static let yourAppIsLocked = appLANG.retrive(label: "your_goodz_app_is_locked")
    static let tapUnlock = appLANG.retrive(label: "tap_unlock_to_proceed.")
    static let unlock = appLANG.retrive(label: "UNLOCK")
    static let authenticateWithFaceID = appLANG.retrive(label: "Authenticate_with_Face_ID_to_continue")
    static let biometricNotAvailable = appLANG.retrive(label: "Biometric_authentication_is_not_available")
    static let authWithPasscode = appLANG.retrive(label: "Authenticate_with_your_passcode")
    static let authFailed = appLANG.retrive(label: "Authentication_failed")
    static let passcodeAuthNotavailable = appLANG.retrive(label: "Passcode_authentication_not_available")
    static let authenticateWithTouchID = appLANG.retrive(label: "Authenticate_with_Touch_ID_to_continue")
    static let authWithBiometrics = appLANG.retrive(label: "Authenticate_using_Face_ID_or_Touch_ID")
    static let HasAuthenticatedWithFaceID = appLANG.retrive(label: "HasAuthenticatedWithFaceID")
    // sell your items
    static let typeOfDeliveryTitle = appLANG.retrive(label: "type_of_delivery_title")
    static let yourProductCouldFitIn = appLANG.retrive(label: "your_product_could_fit_in")
    static let delivery = appLANG.retrive(label: "delivery")
    static let delivered = appLANG.retrive(label: "delivered")
    static let deliveredOn = appLANG.retrive(label: "delivered_on")
    static let conditions = appLANG.retrive(label: "conditions")
    // Orders
    static let Orders = appLANG.retrive(label:"orders")
    static let orderDetails = appLANG.retrive(label:"order_details")
    static let saleDetails = appLANG.retrive(label:"sale_details")
    static let myOrder = appLANG.retrive(label:"my_order")
    static let mySales =  appLANG.retrive(label:"my_sales")
    
    // Profile
    static let goodzPro = appLANG.retrive(label: "goodz_pro")
    static let myStore = appLANG.retrive(label: "my_store")
    static let myOrders = appLANG.retrive(label: "my_orders")
    static let myWallet = appLANG.retrive(label: "my_wallet")
    static let myAds = appLANG.retrive(label: "my_ads")
    static let bundles = appLANG.retrive(label: "bundles")
    static let bundle = appLANG.retrive(label: "bundle")
    static let notifications = appLANG.retrive(label: "notifications")
    static let helpCenter = appLANG.retrive(label: "help_center_title")
    static let settings = appLANG.retrive(label: "settings")
    static let version = appLANG.retrive(label: "version")
    
    // settings
    static let setting = appLANG.retrive(label: "setting")
    static let uploadYourDocument = appLANG.retrive(label: "upload_your_document")
    static let myDocs = appLANG.retrive(label: "My_Documents")
    static let uploadYourDocuments = appLANG.retrive(label: "upload_your_documents")
    static let emiratedID = appLANG.retrive(label: "Emirates ID")
    static let uploadDocuments = appLANG.retrive(label: "upload_documents")
    static let uploadMyDocumentsNow = appLANG.retrive(label: "upload_my_documents_now")
    static let payment = appLANG.retrive(label: "payment")
    static let myAddress = appLANG.retrive(label: "my_address")
    static let logout = appLANG.retrive(label: "logout")
    static let deleteAccount = appLANG.retrive(label: "delete_account")
    
    // Order Summary
    static let orderSummary = appLANG.retrive(label: "order_summary")
    
    // Sale/Order Details
    static let buyerName = appLANG.retrive(label: "buyer_name")
    static let orderId = appLANG.retrive(label: "order_id")
    static let orderPlaced = appLANG.retrive(label: "order_placed")
    static let subtotal = appLANG.retrive(label: "subtotal")
    static let coupon = appLANG.retrive(label: "coupon")
    static let vat5 = appLANG.retrive(label: "vat_5")
    static let totalPrice = appLANG.retrive(label: "total_price")
    static let totalItem = appLANG.retrive(label: "total_item")
    static let paymentMethod = appLANG.retrive(label: "payment_method")
    static let deliveryCost = appLANG.retrive(label: "delivery_cost")
    static let confirmReception = appLANG.retrive(label: "confirm_reception")
    static let reportAProblem = appLANG.retrive(label: "report_a_problem")
    static let confirmReceptionSuccessfull = appLANG.retrive(label: "confirm_reception_successfull")
    
    // Report a Problem
    static let tellUsMore = appLANG.retrive(label: "tell_us_more")
    static let describeTheIssues = appLANG.retrive(label: "describe_the_issues")
    static let pleaseDescribeTheIssues = appLANG.retrive(label: "please_describe_the_issues")
    static let attachAPhoto = appLANG.retrive(label: "attach_a_photo")
    
    // Product details
    static let contactTheSeller = appLANG.retrive(label: "contact_the_seller")
    static let items = appLANG.retrive(label: "items")
    static let item = appLANG.retrive(label: "item")
    static let itemsForSale = appLANG.retrive(label: "items_for_sale")
    static let itemForSale = appLANG.retrive(label: "item_for_sale")
    static let paymentGatewayName = appLANG.retrive(label: "payment_gateway_name")
    static let buyNow = appLANG.retrive(label: "buy_now")
    static let addToCart = appLANG.retrive(label: "add_to_cart")
    static let makeAnOffer = appLANG.retrive(label: "make_an_offer")
    static let description = appLANG.retrive(label: "description")
    static let similarProducts = appLANG.retrive(label: "similar_products")
    static let products = appLANG.retrive(label: "products")
    
    // Edit Store Details
    static let pleaseEnterCompanyName = appLANG.retrive(label: "please_enter_company_name")
    static let pleaseSelectCity = appLANG.retrive(label: "please_select_city")
    static let pleaseSelectArea = appLANG.retrive(label: "please_select_area")
    static let cityNotAvailable = appLANG.retrive(label: "city_not_available")
    static let areaNotAvailable = appLANG.retrive(label: "area_not_available")
    static let pleaseEnterDescription = appLANG.retrive(label: "please_enter_description")
    static let enterCompanyName = appLANG.retrive(label: "enter_company_name")
    static let companyName = appLANG.retrive(label: "company_name")
    static let done = appLANG.retrive(label: "done")
    static let continueTitle = appLANG.retrive(label: "continue")
    static let updateDetails = appLANG.retrive(label: "update_details")
    static let editStore = appLANG.retrive(label: "edit_store")
    static let storeDetail = appLANG.retrive(label: "store_detail")
    static let enterDescription = appLANG.retrive(label: "enter_Description")
    static let storeDetailUpdatedSuccessfully = appLANG.retrive(label: "store_detail_updated_successfully")
    static let pleaseUploadStoreImage = appLANG.retrive(label: "please_upload_store_image")
    
    // pro user
    static let streetAddressVilla : String = appLANG.retrive(label: "street_address_villa_building_etc")
    static let floorApartmentNumber : String = appLANG.retrive(label: "floor_apartment_number_villa_number_")

    static let firstName : String = appLANG.retrive(label: "firstName")
    static let lastName : String = appLANG.retrive(label: "lastName")
    static let fullName : String = appLANG.retrive(label: "full_name")
    static let cityPlaceHolder : String = appLANG.retrive(label: "city_star")
    static let areaPlaceHolder: String = appLANG.retrive(label: "area_star")
    static let streetAddressPlaceHolder : String = appLANG.retrive(label: "streetAddress_star")
    static let floorPlaceHolder : String = appLANG.retrive(label: "floor_star")
    static let idPlaceHolder : String = appLANG.retrive(label: "id_star")
    static let mobilePlaceholder : String = appLANG.retrive(label: "mobile_star")
    static let dobPlaceholder : String = appLANG.retrive(label: "dOB_star")
    static let dob_Placeholder : String = "DOB"//appLANG.retrive(label: "Dob")
    
    // Security
    static let verifyYourEmailAddress : String = appLANG.retrive(label:"verify_your_email_address")
    static let protectYourAccountWithAAafePassword : String = appLANG.retrive(label:"protect_your_account_with_a_safe_password")
    static let twoStepsVerification  : String = appLANG.retrive(label:"two_Steps_Verification ")
    static let confirmTheNewConnection : String = appLANG.retrive(label: "confirm_the_new_connection_with_4_figure_code_sent_directly_to_your_mobile_phone")
    static let connections : String = appLANG.retrive(label:"connections")
    static let viewConnectedDevices : String = appLANG.retrive(label:"view_connected_devices")
    
    /// upload document screen
    static let requested : String = appLANG.retrive(label:"requested")
    static let uploaded : String = appLANG.retrive(label:"uploaded")
    static let pleaseUploadYourEmirates : String = appLANG.retrive(label:"please_upload_your_Emirates_I_to_begin_the_verification_process_and_enjoy_the_full_benefits_of_Goodz")
    static let pleaseUploadYourBankLetter : String = appLANG.retrive(label:"please_upload_your_Bank_Letter_to_begin_the_verification_process_and_enjoy_the_full_benefits_of_Goodz")
    static let emirates : String = appLANG.retrive(label:"emirates_ID")
    static let letter : String = appLANG.retrive(label:"Bank_Letter")
    static let pleaseUploadYour : String = appLANG.retrive(label:"please_upload_your")
    static let toBeginTheverificationProcess : String = appLANG.retrive(label:"to_begin_theverification_process_and_enjoy_the_full_benefits_of_Goodz")
    static let toBeginverificationProcess : String = appLANG.retrive(label:"to_begin_the_verification_process_and_enjoy_the_full_benefits_of_Goodz")
    static let front : String = appLANG.retrive(label:"front")
    static let bankLettermandat : String = appLANG.retrive(label:"bank_letter_(mandatory)")
    static let back : String = appLANG.retrive(label:"back")
    static let weRequireYourEmirates : String = appLANG.retrive(label:"we_require_your_Emirates_ID_for_account_verification_because_it_is_required_by_our_payment_provider_to_wire_some_money_directly_into_your_bank account_and_to_prevent_money_laundering_Your_Emirates_ID_helps_us_verify_your_identity,_ensuring_only_legitimate")
    static let yourSecurityIsOurPriority : String = appLANG.retrive(label:"your_Security_is_Our_Priority")
    static let yourInformationIsUsedSolely : String = appLANG.retrive(label:"your_information_is_used_solely_for_verification_and_is_never_shared_without_your_consent")
    static let uploadMyDocuments : String = appLANG.retrive(label:"upload_My_Documents")
    static let validateChanges : String = appLANG.retrive(label:"validate_Changes")
    static let emiratesIDReceivedOn : String = appLANG.retrive(label:"emirates_ID_received _on:_")
    static let emiratesIDValidatedOn : String = appLANG.retrive(label:"emirates_ID_validated_on:_")
    // Security Email
    static let emailPlaceholder : String = appLANG.retrive(label:"email_star")
    static let sendConfirmationEmail : String = appLANG.retrive(label:"send_a_Confirmation_Email")
    static let changeCurrentEmail : String = appLANG.retrive(label:"change_Current_Email")
    // security password
    static let changePassword : String = appLANG.retrive(label:"change_Password")
    static let passwordRequirementsShouldInclude : String = appLANG.retrive(label:"password_requirements_should_include_a_minimum_of_8_characters_and_a_mix_of_uppercase_lowercase_letters_numbers_and_special_characters_to_enhance_security")
    static let currentPassword : String = appLANG.retrive(label:"current_Password")
    static let newPassword : String = appLANG.retrive(label:"new_Password")
    static let confirmNewPassword : String = appLANG.retrive(label:"confirm_New_Password")
    // reset password
    static let saveNewPassword : String = appLANG.retrive(label:"save_New_Password")
    static let newPasswordPlaceHolder : String = appLANG.retrive(label:"new_password_star")
    static let confirmedPasswordPlaceHolder : String = appLANG.retrive(label:"confirmed_password_star")
    static let resetPassword : String = appLANG.retrive(label:"reset_Password")
    static let pleaseEnterNewPassword : String = appLANG.retrive(label:"please_enter_new_password")
    
    // two step verification
    static let twoSteps : String = appLANG.retrive(label:"two_steps")
    static let wewillSendYou : String = appLANG.retrive(label:"well_send_you_a_4_digit_verification_code_if_theres_a_login_attempt_from_a_device_we_dont_recognise")
    static let Change : String = appLANG.retrive(label:"change")
    static let verified : String = appLANG.retrive(label:"verified")
    static let sendConfirmationSMS : String = appLANG.retrive(label:"send_a_Confirmation_SMS")
    static let protectLoginAttempts : String = appLANG.retrive(label:"protect_login_attempts")
    static let twoStepsVerificationIsActivated : String = appLANG.retrive(label:"two_steps_verification_is_actiVATed_when_you_login_with_your_credentials")
    
    // security connections
    static let Connections : String = appLANG.retrive(label:"connections")
    static let reviewLoginActivity : String = appLANG.retrive(label:"review_login_activity")
    static let eachSessionShowsADeviceLogged : String = appLANG.retrive(label:"each_session_shows_a_device_logged_into_your_Goodz_account._If_you_notice_any_unusual_activity._Log_out_of_that_session.")
    static let now : String = appLANG.retrive(label: "now")
    static let currentDevice : String = appLANG.retrive(label: "current_device")
    
    // notifications
    static let pushNotification : String = appLANG.retrive(label:"push_notification")
    static let no_notification_found : String = appLANG.retrive(label:"no_notification_found")
    static let orderConfirmation : String = appLANG.retrive(label:"order_confirmation")
    static let orderStatus : String = appLANG.retrive(label:"order_status")
    static let newMessageAlert : String = appLANG.retrive(label:"new_message_alert")
    static let newReviewAlert : String = appLANG.retrive(label:"new_review_alert")
    static let favoriteArticleNewPriceAlert : String = appLANG.retrive(label:"favorite_article_new_price_alert")
    static let articleSoldAlert : String = appLANG.retrive(label:"article_sold_alert")
    static let receivedOfferedAlert : String = appLANG.retrive(label:"received_offered_alert")
    static let newFollowerAlert : String = appLANG.retrive(label:"new_follower_alert")
    static let newArticlePostedbytheFollower : String = appLANG.retrive(label:"new_article_posted_by_the_follower")
    static let favoriteArticleSold : String = appLANG.retrive(label:"favorite_article_sold")
    static let authoriseEmailNotification : String = appLANG.retrive(label:"authorise_email_notification")
    static let termsAndCondition : String = appLANG.retrive(label:"terms_and_condition")
    static let sellItemEditedSuccessfully : String = appLANG.retrive(label:"sell_item_edited_successfully")
    static let sellItemAddedSuccessfully : String = appLANG.retrive(label:"sell_item_added_successfully")
   
    ///price and dimension
    static let minPrice : String = appLANG.retrive(label: "min_price")
    static let maxPrice: String = appLANG.retrive(label: "max_price")
    static let enterMinPrice : String = appLANG.retrive(label: "enter_min_price")
    static let enterMaxPrice: String = appLANG.retrive(label: "enter_max_price")
    static let enterWidthCm : String = appLANG.retrive(label: "enter_width_cm")
    static let enterHeightCm : String = appLANG.retrive(label: "enter_height_cm")
    static let enterLengthCm : String = appLANG.retrive(label: "enter_length_cm")
    static let enterWeigthCm : String = appLANG.retrive(label: "Enter_weigth_kg")
    static let pleaseEnterWidthCm : String = appLANG.retrive(label:  "please_enter_width_cm")
    static let pleaseEnterHeightCm : String = appLANG.retrive(label: "please_enter_height_cm")
    static let pleaseEnterLengthCm : String = appLANG.retrive(label: "please_enter_length_cm")
    static let pleaseEnterWeigthCm : String = appLANG.retrive(label: "please_enter_weigth_kg")
    static let pleaseEnterMinPrice : String = appLANG.retrive(label: "please_enter_min_price")
    static let pleaseEnterMaxPrice : String = appLANG.retrive(label: "please_enter_max_price")
    static let areYouSureWantToHideProduct = appLANG.retrive(label:  "are_you_sure_want_to_hide_product")
    static let areYouSureWantToUnHideProduct = appLANG.retrive(label:  "are_you_sure_want_to_unhide_product")
    static let hide = appLANG.retrive(label: "hide_")
    static let areYouSureWantToDeleteproduct = appLANG.retrive(label: "are_you_sure_want_to_delete_product")
    static let pleaseSelectedPickupDate = appLANG.retrive(label: "please_selected_pickup_date")
    static let pleaseSelectedPickupTimeSlot = appLANG.retrive(label: "please_selected_pickup_date_time_slot")
    static let selectDateAndTime = appLANG.retrive(label: "select_date_and_time")
    static let productTitle = appLANG.retrive(label: "product_title")
    static let sellNow = appLANG.retrive(label: "sell_now")
    static let invoiceDownloadedSuccessfully = appLANG.retrive(label: "invoice_downloaded_successfully")
    static let totalFollowers : String = appLANG.retrive(label: "total_followers")
    static let totalReviews : String = appLANG.retrive(label: "total_reviews")
    static let productViews : String = appLANG.retrive(label: "product_views")
    static let productLikes : String = appLANG.retrive(label: "product_likes")
    // chat address
    static let selectPickUpAddress : String = appLANG.retrive(label: "select_pickup_address")
    static let add : String = appLANG.retrive(label: "add")
    static let next : String = appLANG.retrive(label: "next")
    static let youHaveScheduledApickUpOfYourGOODZ : String = appLANG.retrive(label: "you_have_scheduled_a_pick_up_of_your_goodz")
    /// Caption for Item buy sell
    static let giveASecondLifeToYourFurniture : String = appLANG.retrive(label: "give_a_second_life_to_your_furniture")
    static let findTheBestDealsOfTheMarket: String = appLANG.retrive(label: "find_the_best_deals_of_the_market")
    /// HOME``
    static let popularProducts = appLANG.retrive(label:"popular_Products")
    static let popularStores = appLANG.retrive(label:"popular_Stores")
    static let similarProduct = appLANG.retrive(label:"similar_Products")
    static let paymentWith = appLANG.retrive(label:"x_payment_with")
    static let DoorToDoor = appLANG.retrive(label:"door_to_door")
    static let Delivery = appLANG.retrive(label:"delivery")
    static let recentSearch = appLANG.retrive(label:"recent_search")
    static let clearAll = appLANG.retrive(label:"clear_all")
    /// ** Product List
    static let filter = appLANG.retrive(label:"filter")
    static let category = appLANG.retrive(label:"category")
    static let subCategory = appLANG.retrive(label:"sub_Category")
    static let condition = appLANG.retrive(label:"condition")
    static let price = appLANG.retrive(label:"price")
    static let dimensions = appLANG.retrive(label:"dimensions")
    static let result = appLANG.retrive(label:"result")
    static let results = appLANG.retrive(label:"results")
    static let subSubcategory = appLANG.retrive(label: "sub_sub_category")
    /// Chat
    static let inbox = appLANG.retrive(label:"inbox")
    static let block = appLANG.retrive(label:"block")
    static let report = appLANG.retrive(label:"report")
    static let delete = appLANG.retrive(label:"delete")
    static let noMessagesYet = appLANG.retrive(label:"no_messages_yet")
    static let noResultFound = appLANG.retrive(label:"no_Result_Found")
    // pro user upload doc
    static let submittingYourTradeLicense : String = appLANG.retrive(label: "submitting_your_trade_license_and_company_letterhead_establishes_your_companys_legitimacy_on_our_platform")
    static let tradeLicenseAndCompanyLetterhead : String = appLANG.retrive(label: "trade_license_and_company_letterhead")
    static let submittingYour : String = appLANG.retrive(label: "submitting_your")
    static let establishesYourCompanyLegitimacy : String = appLANG.retrive(label: "establishes_your_companys_legitimacy_on_our_platform")
    static let tradeLicense : String = appLANG.retrive(label: "trade_License")
    static let companyLetterHead : String = appLANG.retrive(label: "company_letter_head")
    static let tradeLicenceReceivedOn : String = appLANG.retrive(label: "trade_licence_received_on")
    static let tradeLicenceValidatedOn : String = appLANG.retrive(label: "trade_licence_validated_on")
    static let companyLetterheadReceivedOn : String = appLANG.retrive(label: "company_letterhead_received_on")
    static let companyLetterheadValidatedOn : String = appLANG.retrive(label: "company_letterhead_validated_on")
    ///dashboard
    static let dashboard : String = appLANG.retrive(label: "dashboard")
    static let myFigures : String = appLANG.retrive(label: "my_figures")
    static let myInvoices : String = appLANG.retrive(label: "my_invoices")
    static let totalSales : String = appLANG.retrive(label: "total_sales")
    static let monthly : String = appLANG.retrive(label: "monthly")
    static let salesByCategory : String = appLANG.retrive(label: "sales_by_category")
    static let salesPerCategoryInVolume : String = appLANG.retrive(label: "sales_per_category_in_volume")
    static let storeViews : String = appLANG.retrive(label: "store_views")
    static let yearly : String = appLANG.retrive(label: "yearly")
    static let salesInAED : String = appLANG.retrive(label: "sales_in_AED")
    ///validation
    static let pleaseEnterValidPassword : String = appLANG.retrive(label: "password_shuold_be_minimum_8_characters_at_least_1_Uppercase_Alphabet_1_Lowercase_Alphabet_1_Number_and_1_Special_Character")
    static let pleaseEnterCurrentPassword : String = appLANG.retrive(label: "please_enter_current_password")
    static let pleaseEnterValidCurrentPassword : String = appLANG.retrive(label: "current_password_shuold_be_minimum_8_characters_at_least_1_uppercase_alphabet_1_lowercase_alphabet_1_number_and_1_special_character")
    static let pleaseEnterValidUsername : String = appLANG.retrive(label: "please_enter_valid_username")
    static let pleaseEnterValidPhoneNumber : String = appLANG.retrive(label: "please_enter_valid_phone_number")
    static let pleaseAgreeWithTearmsCondition : String = appLANG.retrive(label: "please_agree_with_tearms_and_condition")
    static let pleaseEnterValidNewPassword : String = appLANG.retrive(label: "new_password_shuold_be_minimum_8_characters_at_least_1_uppercase_alphabet_1_lowercase_alphabet_1_number_and_1_special_character")
    static let pleaseEnterConfirmedPassword : String = appLANG.retrive(label: "please_enter_confirmed_password")
    static let pleaseEnterPrice : String = appLANG.retrive(label: "please_enter_price")
    static let pleaseSelectAddress : String = appLANG.retrive(label: "please_select_address")
    static let pleaseEnterValidFullName : String = appLANG.retrive(label: "please_enter_valid_full_name")
    static let pleaseEnterValidStreetAddress : String = appLANG.retrive(label: "please_enter_valid_street_address")
    static let pleaseEnterValidFloor : String = appLANG.retrive(label: "please_enter_valid_floor")
    static let pleaseSelectTypeOfDelivery : String = appLANG.retrive(label: "please_select_type_of_delivery")
    static let pleaseEnterForYou : String = appLANG.retrive(label: "please_enter_For_You(Price_you_will_earn)")
    static let pleaseEnterDOB : String = appLANG.retrive(label: "please_enter_DOB")
    static let pleaseEnterStoreName : String = appLANG.retrive(label: "please_enter_store_name")
    static let pleaseEnterCity : String = appLANG.retrive(label: "please_enter_City")
    static let pleaseEnterCountry : String = appLANG.retrive(label: "please_enter_country")
    static let pleaseEnterDscription : String = appLANG.retrive(label: "please_enter_description")
    static let pleaseEnterDescribeTheIssues  : String = appLANG.retrive(label: "please_enter_describe_the_issues_")
    static let pleaseAttachApPhoto : String = appLANG.retrive(label: "please_attach_a_photo")
    static let pleaseEnterBankName : String = appLANG.retrive(label: "please_enter_bank_name")
    static let alreadyExistData : String = appLANG.retrive(label: "already_exists_data")
    static let pleaseEnterAccountHolderName : String = appLANG.retrive(label: "please_enter_account_holder_name")
    static let pleaseEnterAccountNumber : String = appLANG.retrive(label: "please_enter_account_aumber")
    static let pleaseEnterIBANNumber : String = appLANG.retrive(label: "please_enter_IBAN_number")
    static let pleaseEnterSWIFTCode : String = appLANG.retrive(label: "please_enter_SWIFT_code")
    static let pleaseAttachBankLetter : String = appLANG.retrive(label: "please_attach_bank_letter")
    static let pleaseEnterNameOfCard : String = appLANG.retrive(label: "please_enter_name_of_card")
    static let pleaseEnterCardNumber : String = appLANG.retrive(label: "please_enter_card_number")
    static let pleaseEnterExpirationDate : String = appLANG.retrive(label: "please_enter_expiration_date")
    static let pleaseEnterValidAccountHolderName : String = appLANG.retrive(label: "please_enter_valid_account_holder_name")
    static let pleaseEnterValidAccountNumber : String = appLANG.retrive(label: "please_enter_valid_account_aumber")
    static let pleaseEnterValidIBANNumber : String = appLANG.retrive(label: "please_enter_valid_IBAN_number")
    static let pleaseEnterValidSWIFTCode : String = appLANG.retrive(label: "please_enter_valid_SWIFT_code")
    static let pleaseEnterValidNameOfCard : String = appLANG.retrive(label: "please_enter_valid_name_of_card")
    static let pleaseEnterValidCardNumber : String = appLANG.retrive(label: "please_enter_valid_card_number")
    static let pleaseEnterValidExpirationDate : String = appLANG.retrive(label: "please_enter_valid_expiration_date")
    static let pleaseSelectPaymentOption : String = appLANG.retrive(label: "please_select_payment_option")
    static let pleaseSelectBoostPlans : String = appLANG.retrive(label: "please_select_boost_plans")
    static let pleaseSelectStoreBoostPlan : String = appLANG.retrive(label: "please_select_store_boost_plan")

    static let pleaseEnterValidName : String = appLANG.retrive(label: "please_enter_valid_name")
    static let pleaseEnterFirstName : String = appLANG.retrive(label: "please_enter_first_name")
    static let pleaseEnterValidFirstName : String = appLANG.retrive(label: "please_enter_valid_first_name")
    static let pleaseEnterLastName : String = appLANG.retrive(label: "please_enter_last_name")
    static let pleaseEnterValidLastName : String = appLANG.retrive(label: "please_enter_valid_last_name")
    static let usernamePlaceholder : String = appLANG.retrive(label: "username_star")
    static let phoneNumberPlaceholder : String = appLANG.retrive(label: "phone_number_star")
    static let passwordPlaceholder : String = appLANG.retrive(label: "password_star")
    static let activeBiometric : String = appLANG.retrive(label: "Active_Biometric")
    static let isBiometricOn : String = appLANG.retrive(label: "isBiometricOn")
    static let byregisteringIConfirmThatIAcceptGoodz : String = appLANG.retrive(label: "by_registering_I_confirm_that_I_accept_Goodzs_Terms_and_Conditions_have_read_the_Privacy_Policy_and_I_am_at_least_18_years_old")
    static let didntReceiveVerificationCodeResend : String = appLANG.retrive(label: "didnt_receive_verification_code_resend")
    static let didntReceiveVerificationCode : String = appLANG.retrive(label: "didnt_receive_verification_code")
    static let enterYourEmailAssociatedWithYourAccount : String = appLANG.retrive(label: "enter_your_email_associated_with_your_account_we_will_send_you_a_verification_code")
    static let enteredOTPIsInvalid : String = appLANG.retrive(label: "entered_OTP_is_invalid.")
    static let confirmedPasswordPlaceholder : String = appLANG.retrive(label: "confirmed_password_star")
    static let newPasswordConfirmPasswordDoesNotMatch : String = appLANG.retrive(label: "new_password_and_confirm_password_does_not_match")
    static let uploadDocumentSuccessfully : String = appLANG.retrive(label: "upload_document_successfully")
    static let expired : String =  appLANG.retrive(label: "expired")
    static let editProfile : String = appLANG.retrive(label: "edit_Profile")
    static let sellAnItem : String = appLANG.retrive(label: "sell_an_item")
    static let review : String = appLANG.retrive(label: "review")
    static let followers : String = appLANG.retrive(label: "followers")
    static let boostNowYourProduct : String = appLANG.retrive(label: "boost_now_your_product")
    static let promoteYourProductAndSellFaster : String = appLANG.retrive(label: "promote_your_product_and_sell_faster")
    static let highlightYourStore : String = appLANG.retrive(label: "highlight_your_store")
    static let getRidOfAllYourItemQuickly : String = appLANG.retrive(label: "get_rid_of_all_your_item_quickly")
    static let readMore : String = appLANG.retrive(label: "read_more")
    static let readLess : String = appLANG.retrive(label: "read_less")
    static let reply : String = appLANG.retrive(label: "reply")
    static let searchFollowers : String = appLANG.retrive(label: "search_followers")
    static let orders : String = appLANG.retrive(label: "orders")
    static let deliverTo : String = appLANG.retrive(label: "deliver_to")
    static let seller : String = appLANG.retrive(label: "seller")
    static let vAT : String = appLANG.retrive(label: "vAT")
    static let pickupDate : String = appLANG.retrive(label: "pickup_Date")
    static let pickupTime : String = appLANG.retrive(label: "pickup_time")
    static let saleId : String = appLANG.retrive(label: "sale_Id")
    static let addNewAddress : String = appLANG.retrive(label: "add_new_address")
    static let fullNamePlaceholder : String = appLANG.retrive(label: "full_name_star")
    static let cityPlaceholder : String = appLANG.retrive(label: "city_star")
    static let areaPlaceholder : String = appLANG.retrive(label: "area_star")
    static let streetAddressPlaceholder : String = appLANG.retrive(label: "street_address_star")
    static let floorPlaceholder : String = appLANG.retrive(label: "floor_star")
    static let streetAddressVillaBuildingEtc : String = appLANG.retrive(label: "street_address_villa_building_etc")
    static let floorApartmentNumberVillaNumber  : String = appLANG.retrive(label: "floor_apartment_number_villa_number_")
    static let addAddress : String = appLANG.retrive(label: "add_Address")
    // wallet flow
    static let wallet : String = appLANG.retrive(label: "wallet")
    static let transactions : String = appLANG.retrive(label: "transactions")
    static let walletSetup : String = appLANG.retrive(label: "wallet_setup")
    static let availableBalance : String = appLANG.retrive(label: "available_balance")
    static let addFunds : String = appLANG.retrive(label: "add_Funds")
    static let withdrawAmount : String = appLANG.retrive(label: "add_funds")
    static let gOODZSavings : String = appLANG.retrive(label: "goodz_savings")
    static let gOODZEarnings : String = appLANG.retrive(label: "GOODZ_Earnings:")
    static let viewAll : String = appLANG.retrive(label: "view_all")
    static let billingAddress : String = appLANG.retrive(label: "billing_address")
    static let paymentOption : String = appLANG.retrive(label: "payment_option")
    static let withdrawalOption : String = appLANG.retrive(label: "withdrawal_option")
    static let yourAccountIsVerifiedAndYourPaymentInfOIsStoredSecurely : String = appLANG.retrive(label: "your_account_is_verified_and_your_payment_info_is_stored_securely")
    static let addBankDetail : String = appLANG.retrive(label: "bank_detail")
    static let bankName : String = appLANG.retrive(label: "bank_name")
    static let enterBankName : String = appLANG.retrive(label: "enter_bank_name")
    static let accountHolderName : String = appLANG.retrive(label: "account_holder_name")
    static let enterAccountHolderName : String = appLANG.retrive(label: "enter_account_holder_name")
    static let enterHolderName : String = appLANG.retrive(label: "enter_holder_name")
    static let accountNumber : String = appLANG.retrive(label: "account_number")
    static let enterAccountNumber : String = appLANG.retrive(label: "enter_account_number")
    static let enterNumber : String = appLANG.retrive(label: "enter_number")
    static let iBANNumber : String = appLANG.retrive(label: "iBAN_Number")
    static let enterIBANNumber : String = appLANG.retrive(label: "enter_IBAN_Number")
    static let sWIFTCode : String = appLANG.retrive(label: "sWIFT_Code")
    static let enterSWIFTCode : String = appLANG.retrive(label: "enter_SWIFT_Code")
    static let bankLetter : String = appLANG.retrive(label: "bank_letter")
    static let creditCard : String = appLANG.retrive(label: "credit_card")
    static let payPal : String = appLANG.retrive(label: "paypal")
    static let nameOfCard : String = appLANG.retrive(label: "name_of_card")
    static let enterNameOfCard : String = appLANG.retrive(label: "enter_name_of_card")
    static let cardNumber : String = appLANG.retrive(label: "card_number")
    static let enterCardNumber : String = appLANG.retrive(label: "enter_card_number")
    static let expirationDate : String = appLANG.retrive(label: "expiration_date")
    static let enterExpirationDate : String = appLANG.retrive(label: "enter_expiration_date")
    static let cVV : String = appLANG.retrive(label: "cvv")
    static let enterCVV : String = appLANG.retrive(label: "enter_CVV")
    static let pleaseEnterCVV : String = appLANG.retrive(label: "please_enter_CVV")
    static let pleaseEnterValidCVV : String = appLANG.retrive(label: "please_enter_valid_CVV")
    static let addPaymentOption  : String = appLANG.retrive(label: "add_payment_option ")
    static let enterAmount : String = appLANG.retrive(label: "enter_amount")
    static let selectDiscount : String = appLANG.retrive(label: "select_discount")
    static let bankDetail : String = appLANG.retrive(label: "bank_Detail")
    static let withdraw  : String = appLANG.retrive(label: "withdraw") + " "
    // my ads
    static let boostItem : String = appLANG.retrive(label: "boost_item")
    static let featuredListing : String = appLANG.retrive(label: "featured_listing")
    static let yourProductWillAppearOnTopOfPeoplesResearches : String = appLANG.retrive(label: "your_product_will_appear_on_top_of_peoples_researches")
    static let boostPlans : String = appLANG.retrive(label: "boost_plans")
    static let bestOffer : String = appLANG.retrive(label: "best_offer")
    static let sellfaster : String = appLANG.retrive(label: "sell_3x_faster")
    static let byBoostingYourStoreYouWillDrive = appLANG.retrive(label: "by_boosting_your_store_you_will_drive_more_traffic_and_receive_more_product_inquiries")
    static let appearInUsersTopSearchResults : String = appLANG.retrive(label: "appear_in_users_top_search_results")
    static let yourStoreWillAppearInTheHomepageAndOnThe : String = appLANG.retrive(label: "your_store_will_appear_in_the_homepage_and_on_the_top_of_peoples_researches")
    static let exploreYourStorePerformance : String = appLANG.retrive(label: "explore_your_stores_performance")
    static let youWillBeAbleToVisualize : String = appLANG.retrive(label: "you_will_be_able_to_visualize_your_daily_reach_on_an_analytics_chart")
    static let active : String = appLANG.retrive(label: "active")
    static let extendYourPlan : String = appLANG.retrive(label: "extend_your_plan")
    static let yourStoreWillAppearInTheHomepage : String = appLANG.retrive(label: "your_store_will_appear_in_the_homepage_and_on_the_top_of_people_researches")
    static let storeMustBeHaveProductsToUse  : String = appLANG.retrive(label: "store_must_be_have_5_products_to_use_this_store_boost_feature.")
    static let toUseAdsFeaturesYouShouldHaveAtLeastOneProductUploadedInYourStore = appLANG.retrive(label: "to_use_ads_features_you_should_have_at_least_one_product_uploaded_in_your_store")
    // bundling products
    static let BundlingProducts : String = appLANG.retrive(label: "bundling_products")
    static let OfferAdiscountFor : String = appLANG.retrive(label: "offer_a_discount_for")
    static let YouCanOfferIncreasingDiscountsBasedOnTheAmounts : String = appLANG.retrive(label: "you_can_offer_increasing_discounts_based_on_the_amounts_spent_by_your_customer_these_discounts_can_help_you_sell_a_larger_number_of_your_items_the_ more_appealing_your_discounts_are_the_faster_you_will_sell")
    static let FirstStageDiscount : String = appLANG.retrive(label: "first_stage_discount")
    static let secondndStageDiscount : String = appLANG.retrive(label: "2nd_stage_discount")
    static let thirdStageDiscount : String = appLANG.retrive(label: "3rd_stage_discount")
    static let discount : String = appLANG.retrive(label: "discount")
    static let activateBundle : String = appLANG.retrive(label: "activate_bundle")
    // help center flow
    static let ourCommitments : String = appLANG.retrive(label: "our_commitments")
    static let legal : String = appLANG.retrive(label: "legal")
    static let account : String = appLANG.retrive(label: "account")
    static let safetyPlatform : String = appLANG.retrive(label: "safety_platform")
    static let shippingAndDelivery : String = appLANG.retrive(label: "shipping_and_delivery")
    static let proTermsAndConditions : String = appLANG.retrive(label: "pro_terms_and_conditions ")
    static let termOfUse : String = appLANG.retrive(label: "term_of_use")
    // 22/12/23
    static let newUsers : String = appLANG.retrive(label: "new_users_")
    static let enterState : String = appLANG.retrive(label: "enter_state")
    static let pleaseEnterState : String = appLANG.retrive(label: "Please Enter State")
    static let cContinue : String = appLANG.retrive(label: "continue")
    static let youCanReachOurCustomerServiceOurLiveChat : String = appLANG.retrive(label: "you_can_reach_our_customer_service_via_our_live_chat")
    static let youCanReachOurCustomerServiceOur : String = appLANG.retrive(label: "you_can_reach_our_customer_service_via_our")
    static let liveChat : String = appLANG.retrive(label: "live_chat")
    static let trackMyOrder : String = appLANG.retrive(label: "track_my_order")
    static let estimationDelivery : String = appLANG.retrive(label: "estimation_delivery")
    static let oOrderId : String = appLANG.retrive(label: "order_Id")
    static let pickedUp : String = appLANG.retrive(label: "picked_up")
    static let shipped : String = appLANG.retrive(label: "shipped")
    static let inTransit : String = appLANG.retrive(label: "in_transit")
    static let applePay : String = appLANG.retrive(label: "apple_pay")
    static let googlePay : String = appLANG.retrive(label: "google_pay")
    static let couponCode : String = appLANG.retrive(label: "coupon_Code")
    static let cart : String = appLANG.retrive(label: "cart")
    static let congratsYourOrderIsComplete : String = appLANG.retrive(label: "congrats_your_order_is_complete")
    static let youCanNowTrackYourDelivery : String = appLANG.retrive(label: "you_can_now_track_your_delivery")
    static let checkSeller  : String = appLANG.retrive(label: "check_seller_")
    static let confirmation : String = appLANG.retrive(label: "confirmation")
    static let boostedItem : String = appLANG.retrive(label: "boosted_item")
    static let editAddress : String = appLANG.retrive(label: "edit_address")
    static let selectAddress : String = appLANG.retrive(label: "select_address")
    static let select : String = appLANG.retrive(label: "select")
    static let pleaseEnterAmount : String = appLANG.retrive(label: "please_enter_amount")
    static let pleaseEnteValidrAmount : String = appLANG.retrive(label: "please_enter_valid_offer_amount")
    static let dob : String = appLANG.retrive(label: "date_of_birth")
    static let country : String = appLANG.retrive(label: "country")
    // order complted
    static let thankYou : String = appLANG.retrive(label: "thank_you")
    static let YourProductWillBeReleasedShortly : String = appLANG.retrive(label: "your_product_will_be_released_shortly")
    static let bundleProducts : String = appLANG.retrive(label: "bundle Products")
    static let priceDetail : String = appLANG.retrive(label: "price_details")
    static let daysRemaining : String = "  " + appLANG.retrive(label: "days_remaining")
    static let notActive : String = appLANG.retrive(label: "not_active")
    static let downloadInvoice : String = appLANG.retrive(label: "download_invoice")
    static let completed : String = appLANG.retrive(label: "completed")
    static let kDiscout : String = appLANG.retrive(label: "kDiscount")
    static let kItem : String = appLANG.retrive(label: "items")
    static let selectCountry : String = appLANG.retrive(label: "select_country")
    //other
    static let addAFile : String = appLANG.retrive(label: "add_a_file")
    static let chooseAfiletypeToAdd : String = appLANG.retrive(label: "choose_a_filetype_to_add")
    static let camera : String = appLANG.retrive(label: "camera")
    static let phoneLibrary : String = appLANG.retrive(label: "phone_library")
    static let video : String = appLANG.retrive(label: "video")
    static let file : String = appLANG.retrive(label: "file")
    static let appDoesNotHaveAccessToYourPhotosToEnableAccessTapSettingsAndTurnOnPhotoLibraryAccess : String = appLANG.retrive(label: "app_does_not_have_access_to_your_photos_to_enable_access_tap_settings_and_turn_on_photo_library_cccess")
    static let AppDoesNotHaveAccessToYourCameraToEnableAccessTapSettingsAndTurnOnCamera : String = appLANG.retrive(label: "app_does_not_have_access_to_your_camera_to_enable_access_tap_settings_and_turn_on_camera")
    static let AppDoesNotHaveAccessToYourVideoToEnableAccessTapSettingsAndTurnOnVideoLibraryAccess : String = appLANG.retrive(label: "app_does_not_have_access_to_your_video_to_enable_access_tap_settings_and_turn_on_video_library_access")
    static let pleaseEnterCouponCode : String = appLANG.retrive(label: "please_enter_coupon_code")
    static let sharingPhoneNumbersOrEmailIDsIsNotAllowed = appLANG.retrive(label: "sharing_phone_numbers_or_email_IDs_is_not_allowed")
    static let areYouSureYouWantToAddItemsForSell = appLANG.retrive(label: "are_you_sure_you_want_to_add_items_for_sell_q")
    static let areYouSureYouWantToEditItemsForSell = appLANG.retrive(label: "are_you_sure_you_want_to_edit_items_for_sell")
    // Our commitment // added by a
   
    static let ourDedicationToThisCause : String = appLANG.retrive(label: "our_dedication_to_this_cause_is_at_the_core_of_everything_we_do_we_believe_that_a_sustainable_future_is_not_just_an_aspiration_but_an_imperative")
    static let ourLatestNews : String = appLANG.retrive(label:"our_latest_news")
    static let weActivelySeekInnoVATive : String = appLANG.retrive(label:"we_actively_seek_innoVATive_ways_to_extend_the_lif_of_products_promote_reuse_and_minimize_resource_depletion")
    static let commitmentTitleOne : String = appLANG.retrive(label:"best_price_guaranteed")
    static let commitmentTitleTwo : String = appLANG.retrive(label:"exclusive_offer")
    static let commitmentTitleThree : String = appLANG.retrive(label:"express_delivery")
    static let commitmentTitleFour : String = appLANG.retrive(label:"secured_marketplace")
    static let commitmentDesOne : String = appLANG.retrive(label:"your_satisfaction_is_our_priority_and_we_believe_that_getting_the_best_value_for_your_money_should_be_effortless_when_you_choose_to_shop_with_us")
    static let commitmentDesTwo : String = appLANG.retrive(label:"we_believe_in_going_the_extra_mile_to_how_our_appreciation_for_your_loyalty")
    static let commitmentDesThree : String = appLANG.retrive(label:"swift_reliable_and_on_your_doorstep_in_a_flash_our_express_delivery_service_is_all_about_convenience")
    static let commitmentDesFour : String = appLANG.retrive(label:"shop_with_confidence_in_our_secured_marketplace_where_your_safety_and_privacy_are_our_top_priorities")
    static let areYouSureYouWantToChangePassword : String = appLANG.retrive(label: "are_you_sure_you_want_to_change_password_q")
    static let areYouSureYouWantToResetPassword : String = appLANG.retrive(label: "are_you_sure_you_want_to_reset_password_q")
    static let areYouSureYouWantToChangeCurrentEmail : String = appLANG.retrive(label: "are_you_sure_you_want_to_change_current_email_q")
    static let areYouSureYouWantToPurchaseAllProduct : String = appLANG.retrive(label: "are_you_sure_you_want_to_purchase_product_q")
    static let areYouSureYouWantToChangeMobile : String = appLANG.retrive(label: "are_you_sure_you_want_to_change_mobile_q")
    static let areYouSureYouWantToUploadYourDocuments :String = appLANG.retrive(label: "are_you_sure_you_want_to_upload_your_documents_q")
    static let areYouSureYouWantToUpdateYourDocuments :String = appLANG.retrive(label: "are_you_sure_you_want_to_update_your_documents_q")
    static let pleaseEnterAtleastOneStageAmount : String = appLANG.retrive(label: "please_enter_at_least_one_stage_amount")
    // chat suggestion view
    static let chatMsgOne : String = appLANG.retrive(label: "chat_msg_one")
    static let chatMsgTwo : String = appLANG.retrive(label: "chat_msg_two")
    static let chatMsgThree : String = appLANG.retrive(label: "chat_msg_three")
    static let myFavorites : String = appLANG.retrive(label: "my_favorites")
    static let buyInBundle : String = appLANG.retrive(label: "buy_in_bundle")
    static let resetPasswordSuccessfully : String = appLANG.retrive(label: "reset_password_successfully")
    static let otpResendSuccessfully : String = appLANG.retrive(label: "otp_resend_successfully")
    static let deliveryStatus : String = appLANG.retrive(label: "delivery_status")
    static let reportAddedSuccessfully : String = appLANG.retrive(label: "report_added_successfully")
    static let yourPaymentHasBeenSuccessfullyProcessed : String = appLANG.retrive(label: "your_payment_has_been_successfully_processed")
    static let blockUser : String = appLANG.retrive(label: "block_user")
    static let areYouSureYouWantToBlockThisUser : String = appLANG.retrive(label: "are_you_sure_you_want_to_block_this_user")
    static let areYouSureYouWantToUnBlockThisUser : String = appLANG.retrive(label: "are_you_sure_you_want_to_unblock_this_user")
    static let unblock : String = appLANG.retrive(label: "unblock")
    
    static let reportUser : String = appLANG.retrive(label: "report_user")
    static let areYouSureYouWantToReportThisUser : String = appLANG.retrive(label: "are_you_sure_you_want_to_report_this_user")
    static let deleteChat : String = appLANG.retrive(label: "delete_chat")
    static let areYouSureYouWantToDeleteThisChat : String = appLANG.retrive(label: "are_you_sure_you_want_to_delete_this_chat")
    static let chooseAPickupAddress : String = appLANG.retrive(label: "choose_a_pickup_ddress")
    static let minPricelessthanMaxprive : String = appLANG.retrive(label: "the_minimum_price_is_lower_than_the_maximum_price")
    //popup
    static let no : String = appLANG.retrive(label: "no")
    static let yes : String = appLANG.retrive(label: "yes")
    static let update : String = appLANG.retrive(label: "update")
    static let exit : String = appLANG.retrive(label: "exit")
    static let updateAvailable : String = appLANG.retrive(label: "update_available")
    static let aNewVerisonOfGoodzAppIsAvailable : String = appLANG.retrive(label: "a_new_version_of_goodz_app_is_available")
    static let weekly : String = appLANG.retrive(label: "weekly")
    static let itsAGoodzDea : String = appLANG.retrive(label: "its_a_goodz_deal")
    static let goodzWalletCashback : String = appLANG.retrive(label: "goodz_wallet_cashback")
    static let registerAsUser : String = appLANG.retrive(label: "register_as_user")
    static let registerAsCompany : String = appLANG.retrive(label: "register_as_company")
    //Review
    
    static let addReview : String = appLANG.retrive(label: "add_review")
    static let how_would_you_like_this : String = appLANG.retrive(label: "how_would_you_like_this")
    static let how_would_you_rate_this_product : String = appLANG.retrive(label: "how_would_you_rate_this_store")
    static let startWritingHere : String = appLANG.retrive(label: "start_writing_here")
    static let chooseYourFavoriteOption : String = appLANG.retrive(label:  "choose_your_favorite_option :")
    
    static let balance : String = appLANG.retrive(label: "balance")
    static let useMyCashback : String = appLANG.retrive(label: "use_my_cashback")
    static let yourProductBoostShortly : String = appLANG.retrive(label: "your_product_boost_shortly")
    static let yourStoreBoostShortly : String = appLANG.retrive(label: "your_store_boost_shortly")
    static let reach_Estimation : String = appLANG.retrive(label: "reach_estimation")
    static let clicksOnYourApplication : String = appLANG.retrive(label: "clicks_on_your_application")
    static let paymentOf : String = appLANG.retrive(label: "payment_of")
    static let off : String = appLANG.retrive(label: "off")
    static let kRemove : String = appLANG.retrive(label: "remove")
    static let getUpTo : String = appLANG.retrive(label: "get_up_to")
    static let free : String = appLANG.retrive(label: "free")
    static let sellInfo : String = appLANG.retrive(label: "sell_info_mobile")
    
    //wallet
    static let remaining_days_to_use_your_cashback : String = appLANG.retrive(label: "remaining_days_to_use_your_cashback")
    
    static let pleaseUploadYourDocumentForSubscription : String = appLANG.retrive(label: "please_upload_your_document_for_subscription")
    static let YourDocumentsAreUnderReviewOnceTheyAreApprovedYouWillBeAbleToAccessTheDashboard : String = appLANG.retrive(label: "your_documents_are_under_review_once_they_are_approved_you_will_be_able_to_access_the_dashboard")
    static let rejected : String = appLANG.retrive(label: "rejected")
    static let pending : String = appLANG.retrive(label: "pending")
    static let approved : String = appLANG.retrive(label: "approved")
    static let updateYourProfile :String = appLANG.retrive(label: "update_your_profile")
    static let priceValidation : String = appLANG.retrive(label: "selling_price_cannot_be_greater_than_brand_new_price")
    static let pleaseEnterbrandnewPrice  = appLANG.retrive(label: "please_enter_brand_new_price")
    static let pleaseEnterValidbrandnewPrice  = appLANG.retrive(label: "please_enter_valid_brand_new_price")
    static let pleaseEnterValidSellingPrice  = appLANG.retrive(label: "please_enter_valid_selling_price")
    static let pleaseEnterValidSellingPriceForYou  = appLANG.retrive(label: "please_enter_valid_selling_price_for_you")
    static let deliveryType = appLANG.retrive(label: "delivery_type")
    static let selectColor = appLANG.retrive(label: "please_select_color")
    static let selectmaterial = appLANG.retrive(label: "please_select_material")
    static let notificationSettings = appLANG.retrive(label: "notification_settings")
    static let negotiationOffer = appLANG.retrive(label: "negotiation_offer")
    static let pleaseUploadAllDocument = appLANG.retrive(label: "please_upload_all_document")
    static let pleaseUploadBankLetter = appLANG.retrive(label: "please_upload_bank_letter")
    static let pleaseUploadtradeLicence = appLANG.retrive(label: "please_upload_trade_licence")

    static let pleaseEnterComment = appLANG.retrive(label: "please_enter_comment")
    
    static let pleaseEnterFirstStageAmount = appLANG.retrive(label: "please_enter_first_stage_amount")
    static let pleaseSelectFirstStageDiscount = appLANG.retrive(label: "please_select_first_stage_discount")
    static let pleaseEnterSecondStageAmount = appLANG.retrive(label: "please_enter_second_stage_amount")
    static let secondStageAmountShouldBeHigherThanFirstStageAmount = appLANG.retrive(label: "second_stage_amount_should_be_higher_than_first_stage_amount")
    static let pleaseSelectSecondStageDiscount = appLANG.retrive(label: "please_select_second_stage_discount")
    static let secondStageDiscountShouldBeHigherThanFirstStageDiscount = appLANG.retrive(label: "second_stage_discount_should_be_higher_than_first_stage_discount")
    static let pleaseEnterThirdStageAmount = appLANG.retrive(label: "please_enter_third_stage_amount")
    static let thirdStageAmountShouldBeHigherThanSecondStageAmount = appLANG.retrive(label: "third_stage_amount_should_be_higher_than_second_stage_amount")
    static let pleaseSelectThirdStageDiscount = appLANG.retrive(label: "please_select_third_stage_discount")
    static let thirdStageDiscountShouldBeHigherThanSecondStageDiscount = appLANG.retrive(label: "third_stage_discount_should_be_higher_than_second_stage_discount")
    static let yourBundleProductHasBeenActivated = appLANG.retrive(label: "your_bundle_product_has_been_activated")
    static let ToMakeABuyInBundlePurchaseMoreThanOneProductIsRequired = appLANG.retrive(label: "to_make_a_buy_in_bundle_purchase_more_than_one_product_is_required")
    static let backToHome = appLANG.retrive(label: "back_to_home")
    static let addAnotherProduct = appLANG.retrive(label: "add_another_product")
    static let continueShopping = appLANG.retrive(label: "continue_shopping")
    static let buyYourFurnitureResponsively = appLANG.retrive(label: "home_bottom_section_head")
    static let aLittleGestureForThePlanetMakesBigDifferences = appLANG.retrive(label: "home_bottom_section_content")
    static let kgOfWoodSavedToday = appLANG.retrive(label: "kg_of_wood_saved_today")
    static let makeOfferThatAreLowerThanOfTheSellingPrice = appLANG.retrive(label: "make_offer_that_are_lower_than_40_of_the_selling_price")
    static let comment = appLANG.retrive(label: "comment")
    static let reason = appLANG.retrive(label: "reason")
    static let pleaseEnterReason = appLANG.retrive(label: "please_enter_reason")
    static let thisAddressWillEitherBeUsedForPickupForTheDeliveryOptionOrWillBeProvidedToTheBuyerOnlyOnceThePurchaseIsFinalizedOnThePlatform = appLANG.retrive(label: "this_address_will_either_be_used_for_pickup_for_the_delivery_option_or_will_be_provided_to_the_buyer_only_once_the_purchase_is_finalized_on_the_platform")
    static let aed = appLANG.retrive(label: "sell_price_placeholder")
    static let unhide = appLANG.retrive(label: "Unhide")
    static let makeOfferThatAreLowerThan = appLANG.retrive(label: "make_offer_that_are_lower_than")
    static let ofTheSellingPrice = appLANG.retrive(label: "of_the_selling_price")
//    static let = appLANG.retrive(label: "")
    static let theOptimalSellingPriceIs = appLANG.retrive(label: "the_optimal_selling_price_is") + " "
    static let reduceYourPriceBy = ". " + appLANG.retrive(label: "reduce_your_price_by") + "  "
    static let toReachThatPrice = " " + appLANG.retrive(label: "to_reach_that_price")
    static let yourOfferNeedsToBeAtLeast = appLANG.retrive(label: "your_offer_needs_to_be_at_least")
    static let toBoostYourItemsChanceSellingPrice = appLANG.retrive(label: "to_boost_your_items_chance_selling_price")
    static let apply = appLANG.retrive(label: "apply")
    static let clearBundle = appLANG.retrive(label: "clear_bundle")
    static let offerAlreadyAccepted = appLANG.retrive(label: "offer_already_accepted")
    static let integratedLogisticSolution = appLANG.retrive(label: "integrated_logistic_solution")
    static let gainVisibility = appLANG.retrive(label: "gain_visibility")
    static let generateAdditionalRevenue = appLANG.retrive(label: "generate_additional_revenue")
    static let customizedDashboard = appLANG.retrive(label: "customized_dashboard")
    static let addStocks = appLANG.retrive(label: "add_stocks")
    static let prioritySupport = appLANG.retrive(label: "priority_support")
    static let reduceYourBuyerProductionFee = appLANG.retrive(label: "reduce_your_buyer_production_fee")
    static let accessToAnUnlimitedOnlineCommunityIfCativeBuyers = appLANG.retrive(label: "access_to_an_unlimited_online_community_if_cative_buyers")
    static let boostEarningsWith_a_simplifiedOnlinePresence = appLANG.retrive(label: "boost_earnings_with_a_simplified_online_presence")
    static let accessToDetailedInsightsAndAnalyseYourStorePerformance = appLANG.retrive(label: "access_to_detailed_insights_and_analyse_your_store_performance")
    static let unlockYourStockListingPossibilitiesForMultipleItems = appLANG.retrive(label: "unlock_your_stock_listing_possibilities_for_multiple_items")
    static let enjoy_a_dedicatedPriorityProSupport = appLANG.retrive(label: "enjoy_a_dedicated_priority_pro_support")
    static let enjoyGoodzProBenefits = appLANG.retrive(label: "enjoy_goodz_pro_benefits")
    static let subscribeNow = appLANG.retrive(label: "subscribe_now")
    static let goBackToYourBoost = appLANG.retrive(label: "go_back_to_your_boost")
    static let sellFasterDescItem = appLANG.retrive(label: "sell_faster_desc_item")
    static let appearInUserDescItem = appLANG.retrive(label: "appear_in_user_desc_item")
    static let storePerformanceDescItem = appLANG.retrive(label: "store_performance_desc_item")
    static let modifybundleBtnTitle = appLANG.retrive(label: "modify_bundle")
    
    
}
