//
//  StringScheme+API.swift
//  Goodz
//
//  Created by Priyanka Poojara on 01/01/24.
//

import UIKit

public struct APIEndpoint {
    static let register = "v1/register"
    static let login = "v1/login"
    static let verifyOTP = "v1/verify_otp"
    static let resendOTP = "v1/resend_otp"
    static let forgotPassword = "v1/forgot_password"
    static let resetPassword = "v1/reset_password"
    static let general = "v1/general"
    static let label = "v1/label"
    static let countryList = "v1/country_list"
    static let categoryCollection = "v1/category_collection"
    static let categoriesSub = "v1/categories_sub"
    static let categoriesMain = "v1/categories_main"
    static let getProfile = "v1/get_profile"
    static let addFavRemoveFav = "v1/add_fav_remove_fav"
    static let editProfile = "v1/edit_profile "
    static let contactUs = "v1/contact_us"
    static let cms = "v1/cms"
    static let faq = "v1/faq_data"
    static let myAddressList = "v1/my_address_list"
    static let getCities = "v1/get_cities"
    static let getAreas = "v1/get_areas"
    static let addEditAddress = "v1/add_edit_address"
    static let deleteAddress = "v1/delete_address"
    static let productList = "v1/product_list"
    static let storeList = "v1/store_list"
    static let storeDetail = "v1/store_detail"
    static let storeReviews = "v1/store_reviews"
    static let reviewsReply = "v1/reviews_reply"
    static let storeFollowers = "v1/store_followers"
    static let followUnfollowStore = "v1/follow_unfollow_store"
    static let deliveryMethodsList = "v1/delivery_methods_list"
    static let getConditions = "v1/get_conditions"
    static let getBrands = "v1/get_brands"
    static let deleteAccount = "v1/delete_account"
    static let logoutAccount = "v1/logout_account"
    static let sortList = "v1/sort_list"
    static let addCart = "v1/add_cart"
    static let deliveryType = "v1/delivery_type"
    static let productDetails = "v1/product_details"
    static let getCustomization = "v1/get_customization"
    static let saveCustomization = "v1/save_customization"
    static let favoriteProductList = "v1/favorite_product_list"
    static let removeAllFavorites = "v1/remove_all_favorites"
    static let bundleProductList = "v1/bundle_product_list"
    static let addRemoveBundle = "v1/add_remove_bundle"
    static let bundleDeleteCart = "v1/bundle_delete_cart"
    static let sellItems = "v1/sell_items"
    static let getColors = "v1/get_colors"
    static let getMaterial = "v1/get_material"
    static let bundleCartProductList = "v1/bundle_cart_product_list"
    static let cartList = "v1/cart_list"
    static let deleteCart = "v1/delete_cart"
    static let updateCartDeliveryMethod = "v1/update_cart_delivery_method"
    static let similarProductList = "v1/similar_product_list"
    static let setDefaultAddress = "v1/set_default_address"
    static let home = "v1/home"
    static let homeV2 = "v2/home"
    static let getorders = "v1/get_orders"
    static let orderDetails = "v2/order_details"
    static let confirmReception = "v1/confirm_reception"
    static let reportAproblem = "v1/report_a_problem"
    static let myAdsItems = "v1/my_ads_items"
    static let boostItem = "v1/boost_item"
    static let boostItemInfo = "v1/boost_item_info"
    static let makeAnOffer = "v1/make_an_offer"
    static let getChatList = "v1/get_chat_list"
    static let getChatDetails = "v2/get_chat_details"
    static let sendMessage = "v1/send_message"
    static let pinUnpinItem = "v1/pin_unpin_item"
    static let bundlingProducts = "v1/bundling_products"
    static let offerAcceptDecline = "v1/offer_accept_decline"
    static let uploadDocuments = "v1/upload_documents"
    static let getUploadedDocuments = "v1/get_uploaded_documents"
    static let boostedItemInfo = "v1/boosted_item_info"
    static let verifyChangeEmailOtp = "v1/verify_change_email_otp"
    static let changeCurrentEmail = "v1/change_current_email"
    static let changePassword = "v1/change_password"
    static let blockUser = "v1/block_user"
    static let reportUser = "v1/report_user"
    static let boostStoreInfo = "v1/boost_store_info"
    static let boostedStoreInfo = "v1/boosted_store_info"
    static let deleteItem = "v1/delete_item"
    static let hideItem = "v1/hide_item"
    static let getSellList = "v1/get_sell_list"
    static let sellDetails = "v2/sell_details"
    static let editStore = "v1/edit_store"
    static let deleteUser = "v1/delete_user"
    static let editItem = "v1/edit_item"
    static let myStore = "v1/my_store"
    static let contactUsChat = "v1/contact_us_chat"
    static let getTimeSlots = "v1/get_time_slots"
    static let setPickupDateTime = "v1/set_pickup_date_time"
    static let totalSales = "v1/total_sales"
    static let myFiguresStore = "v1/my_figures_store"
    static let storeViews = "v1/store_views"
    static let myInvoices = "v1/my_invoices"
    static let getPushNotificationList = "v1/get_push_notification_list"
    static let socialRegister = "v1/social_register"
    static let sellItemUploadMedia = "v1/sell_item_upload_media"
    static let sellItemDeleteMedia = "v1/sell_item_delete_media"
    static let getPickupAddress = "v1/get_pickup_address"
    static let setPickupAddress = "v1/set_pickup_address"
    static let proceedToCheckout = "v1/proceed_to_checkout"
    static let chat_update_pickup_availability = "v2/chat/update-pickup-availability"
    static let chat_confirm_pickup_slot = "v2/chat/confirm-pickup-slot"
    
    static let chat_add_pickup_slots = "v2/chat/add-pickup-slots"
    
    static let confirm_reception = "v2/confirm-reception"
    
    static let priorityContact = "v1/priority_contact"
    static let getNotificationStatusList = "v1/get_notification_status_list"
    static let updateNotificationStatus = "v1/update_notification_status"
    static let addOrder = "v1/add_order"
    static let verifyChangeMobileOtp = "v1/verify_change_mobile_otp"
    static let editMobileNo = "v1/edit_mobile_no"
    static let getTwoStepVerificationStatus = "v1/get_two_step_verification_status"
    static let updateTwoStepVerificationStatus = "v1/update_two_step_verification_status"
    static let getConnections = "v1/get_connections"
    static let addOrderBundle = "v1/add_order_bundle"
    static let editProductDetails = "v1/edit_product_details"
    static let subscribeProSeller = "v1/subscribe_pro_seller"
    static let addStoreReview = "v1/add_store_review"
    static let myWalletDetails = "v1/my_wallet_details"
    static let walletTransactionList = "v1/wallet_transaction_list"
    static let getWalletSetup = "v1/get_wallet_setup"
    static let addBankDetail = "v1/add_bank_detail"
    static let deleteBankDetail = "v1/delete_bank_detail"
    static let changeBankDetail = "v1/change_bank_detail"
    static let salesByCategory = "v1/sales_by_category"
    static let trackOrderStatus = "v1/track_order_status"
    static let handlePaymentCancel = "v1/handle-payment/cancel"
    static let handlePaymentSuccess = "v1/handle-payment/success"
    
    static let reportProblem = "v2/report-problem"
    
    
    
    
}
